export const userActions = {
    LOGIN_SUCCEED: "LOGIN_SUCCEED",
    UPDATE_IS_AUTHENTICATED:"UPDATE_IS_AUTHENTICATED",
    LOGOUT: "LOGOUT",
    ADD_LOGGED_USER : "ADD_LOGGED_USER",
    RENEW_TOKEN: "RENEW_TOKEN"
  };
  